name: Build and Release EXE

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish .NET App
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o ./publish

      - name: Delete PDB file
        run: Remove-Item ./publish/CosmosSchemaCloner.pdb -Force

      - name: Add config.txt file
        run: |
          echo azureDbConnectionString=YOUR_AZURE_COSMOS_DB_CONNECTION_STRING > ./publish/config.txt
          echo emulatorDbConnectionString=YOUR_EMULATOR_CONNECTION_STRING >> ./publish/config.txt

      - name: Zip the output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./CosmosSchemaCloner.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: ./CosmosSchemaCloner.zip
          token: '${{ secrets.GH_PAT }}'
